In [1]:
import numpy as np

In [2]:
b=np.array([5,6,7,8,9])

In [3]:
type(b)

numpy.ndarray

In [4]:
c=np.array([5,6,7,8,9])

In [8]:
c

array([5, 6, 7, 8, 9])

In [12]:
for i in c:
    print(type(i))

<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


In [13]:
a=np.array([3.1,4.5,6.3,7.8])

In [14]:
for i in a:
    print(type(i))

<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>


In [15]:
c=np.array([5,6,7,8,9.8])

In [16]:
for i in c:
    print(type(i))

<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>


In [17]:
for i in c:
    print((i))

5.0
6.0
7.0
8.0
9.8


In [24]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
np.ones(8,dtype="int32")

array([1, 1, 1, 1, 1, 1, 1, 1])

In [25]:
np.full(8,7)

array([7, 7, 7, 7, 7, 7, 7, 7])

In [26]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [29]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [31]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [33]:
np.random.rand(3,5)

array([[0.10738303, 0.95516316, 0.41516365, 0.06597435, 0.57139046],
       [0.93845835, 0.19570163, 0.79365197, 0.36899787, 0.18165749],
       [0.34550973, 0.34944346, 0.77174668, 0.47259643, 0.89825752]])

In [37]:
np.random.normal(0,11,(3,3))

array([[-0.74180551, -4.75762695, 14.14834526],
       [-4.54367001, -5.82834955,  1.16292616],
       [18.47150156, 12.11640711, 18.09783954]])

In [39]:
np.random.randint(0,10,8)

array([5, 3, 9, 0, 9, 6, 8, 8])

In [40]:
np.random.randint(0,11,(3,3))

array([[4, 2, 4],
       [9, 8, 1],
       [3, 5, 8]])

In [41]:
a=np.random.randint(0,11,size=10)

In [42]:
a

array([ 8,  3,  8, 10,  0,  2,  1,  2,  4,  6])

In [45]:
a.ndim 

1

In [49]:
b=np.random.randint(0,11,(3,3))

In [51]:
b.ndim

2

In [52]:
b.shape

(3, 3)

In [53]:
a.shape

(10,)

In [55]:
a.size

10